const express = require("express")
const usercontroller = require("../controller/usercontroller")
const router = express.Router()
router.post("/register", usercontroller.addUser)
router.get("/login", usercontroller.userLogin)
